changed deletion of nodes from recursive dfs
memgraph/mage pull request #141
Opened 2022-05-02 15:50 UTC by brunos252

### Description

Max flow was failing because the DFS used for finding paths for flow which is recursive, when returning from a call, for some reason `path = path[:-2]` deleted the same two elements multiple times, leaving edges in path that shouldn't be there. `del path[-2:]` works.

### Pull request type

- [x] Bugfix
- [ ] Algorithm/Module
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Related issues

#140 

######################################

### Reviewer checklist (the reviewer checks this part)
#### Module/Algorithm
- [ ] Core algorithm/module implementation
- [ ] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [ ] End-to-end tests
- [ ] Code documentation
- [ ] README short description
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)

######################################

2022-05-03 09:09 UTC, antoniofilipovic commented on python/max_flow.py
> +    del path[-2:]
I am curious, why this didn't work 😄

2022-05-03 09:09 UTC, antoniofilipovic approved these changes

2022-05-03 09:11 UTC, antepusic approved these changes

2022-05-04 10:29 UTC, jmatak approved these changes

2022-05-04 10:33 UTC, antoniofilipovic requested changes
Note, add E2E test for this case before merging it, as noted on Slack by @jmatak

2022-05-06 09:00 UTC, antoniofilipovic approved these changes

2022-05-06 11:59 UTC, antoniofilipovic approved these changes

2022-05-06 12:01 UTC, merged