Implemented coll.contains and wrote tests
memgraph/mage pull request #240
Opened 2023-07-19 14:53 UTC by mpintaric55334

### Description
Implemented coll.contains and wrote tests for it

### Pull request type

- [ ] Algorithm/Module

2023-07-19 22:38 UTC, antoniofilipovic requested changes
Good work, left few c++ comments and styling guides

2023-07-19 22:38 UTC, antoniofilipovic commented on cpp/collections_module/algorithms/collections.hpp
> +    mgp::List list=arguments[0].ValueList();
`const mgp::List &` so that you avoid copies

2023-07-19 22:38 UTC, antoniofilipovic commented on cpp/collections_module/algorithms/collections.hpp
> +    mgp::Value value=arguments[1];
`const mgp::Value &`

2023-07-19 22:38 UTC, antoniofilipovic commented on cpp/collections_module/algorithms/collections.hpp
> +    bool contains_value=false;
```suggestion
    bool contains_value{false};
```

2023-07-19 22:38 UTC, antoniofilipovic commented on cpp/collections_module/algorithms/collections.hpp
> +    if(list.Size()==0 || list.Empty()){
Shouldn't this size() or empty be the same?

2023-07-19 22:38 UTC, antoniofilipovic commented on cpp/collections_module/algorithms/collections.hpp
> +      contains_value=false;
you can set value on record here and use "early return" concept, you can check it here: https://medium.com/swlh/return-early-pattern-3d18a41bba8

2023-07-19 22:38 UTC, antoniofilipovic commented on cpp/collections_module/algorithms/collections.hpp
> +    }else{
now you wouldn't need else branch with early return

2023-07-19 22:38 UTC, antoniofilipovic commented on cpp/collections_module/algorithms/collections.hpp
> +      for(size_t i=0;i<list.Size();i++){
`const size_t `

2023-07-19 22:38 UTC, antoniofilipovic commented on cpp/collections_module/algorithms/collections.hpp
> +    record.Insert("output",contains_value);
set "output" as global variable. You can check Ivan's PRs

2023-07-19 22:38 UTC, antoniofilipovic commented on cpp/collections_module/algorithms/collections.hpp
> +}
This red circle means that empty line is missing. Please add empty line to other files too

2023-07-19 22:38 UTC, antoniofilipovic commented on e2e/collections_test/test_contains/test.yml
> +  - output: false
Did you check somehow that this was called? I am not sure if it was by code in "test_module.py" which is calling only one "query". But nevertheless, I would split these in different files as they are effectively different tests, and this was practice until now.

2023-07-20 09:09 UTC, mpintaric55334 commented on cpp/collections_module/algorithms/collections.hpp
> +      for(size_t i=0;i<list.Size();i++){
How would I then increase i, if its constant

2023-07-21 13:32 UTC, antoniofilipovic requested changes
All seems good, just run clang-tidy format

2023-07-24 09:44 UTC, antoniofilipovic commented on e2e/collections_test/test_contains1/test.yml
> +
You have too many empty lines here now :joy:

2023-07-24 09:44 UTC, antoniofilipovic commented on e2e/collections_test/test_contains3/test.yml
> +
And here one to many I think

2023-07-24 09:44 UTC, antoniofilipovic commented on e2e/collections_test/test_contains4/test.yml
> +
Here also one to many empty line

2023-07-24 09:45 UTC, antoniofilipovic commented on e2e/collections_test/test_contains5/test.yml
> +
This shouldn't also be like this, you can check input.cyp of this test, this is how it is supposed to be :smile:

2023-07-24 09:45 UTC, antoniofilipovic reviewed
Please just refactor to algorithms.cpp and algorithms.hpp and then that should be it

2023-07-25 08:46 UTC, antoniofilipovic approved these changes
Good to go

2023-07-25 12:50 UTC, merged