Wrote collections.min and tests
memgraph/mage pull request #249
Opened 2023-07-24 08:20 UTC by mpintaric55334

Implemented collections.min and wrote tests

2023-07-24 10:20 UTC, antoniofilipovic commented on cpp/collections_module/algorithms/collections.hpp
> +void min(mgp_list *args, mgp_graph *memgraph_graph, mgp_result *result, mgp_memory *memory) {
Naming, here it should be called `Min`

2023-07-24 10:24 UTC, antoniofilipovic commented on cpp/collections_module/algorithms/collections.hpp
> +    mgp::Value min = list[0];
you can do it like this too:
`mgp::Value min{std::move(list[0])};`

2023-07-24 10:26 UTC, antoniofilipovic commented on cpp/collections_module/algorithms/collections.hpp
> +      if (list[i].Type() != type && !(list[0].IsNumeric() && list[i].IsNumeric())) {
what are you doing with list[0]? I think you can use move above and cache in some variable, `bool isListNumeric = list[0].isNumeric()`.

But do that before you move value from list

2023-07-24 10:28 UTC, antoniofilipovic commented on e2e/collections_test/test1/test.yml
> +
You somehow have empty line and then there is this red circle :joy: try deleting one line and then it should be okay, but press enter after `- min: 1` line

2023-07-24 10:28 UTC, antoniofilipovic requested changes
Please also refactor as we talked on Slack

2023-07-24 12:19 UTC, mpintaric55334 commented on cpp/collections_module/algorithms/collections.hpp
> +    }
Neo4j returns null, i thought an exception made more sense here, but can change it to null if you'd like

2023-07-25 10:27 UTC, antoniofilipovic commented on cpp/collections_module/algorithms/collections.hpp
> +    }
I think it makes more sense as it is not breaking behaviour

2023-07-25 10:28 UTC, antoniofilipovic commented on cpp/collections_module/algorithm/algorithm.cpp
> +      throw mgp::ValueException("Empty input list");
Change this to return null

2023-07-25 10:29 UTC, antoniofilipovic commented on cpp/collections_module/algorithm/algorithm.cpp
> +      throw mgp::ValueException("Empty input list");
It makes more sense as it is not breaking behaviour

2023-07-25 10:29 UTC, antoniofilipovic commented on cpp/collections_module/algorithm/algorithm.cpp
> +    }
Won't this break on our mgp::Value side where we compare?

2023-07-25 10:47 UTC, antoniofilipovic approved these changes
Just fix this couple of stuff and it can be merged

2023-07-25 13:28 UTC, merged