[E-ivan < T396] implement setKey
memgraph/mage pull request #260
Opened 2023-07-26 08:49 UTC by imilinovic

### Description

Implement setKey

### Pull request type

- [ ] Bugfix
- [X] Algorithm/Module
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

######################################

### Reviewer checklist (the reviewer checks this part)
#### Module/Algorithm
- [ ] Core algorithm/module implementation
- [ ] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [ ] End-to-end tests
- [ ] Code documentation
- [ ] README short description
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)
- [ ] Update GQLALchemy signatures in [query builder](https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/graph_algorithms/query_builder.py  ) using [query module signature generator](https://github.com/memgraph/gqlalchemy/blob/main/scripts/query_module_signature_generator.py)

######################################

2023-07-26 10:43 UTC, antoniofilipovic requested changes
Few small changes

2023-07-27 08:37 UTC, imilinovic commented on cpp/map_module/algorithm/map.cpp
> +    const auto &value = arguments[2];
Just a general question,
when is one style prefered over the other
`const auto variable{argument}`
vs
`const auto variable = argument`

2023-07-27 08:54 UTC, antoniofilipovic commented on cpp/map_module/algorithm/map.hpp
> +constexpr const std::string_view kProcedureSetKey = "setKey";
I think it makes sesne to call this function `set_key` as this will be consistent with rest of our functions

2023-07-27 09:03 UTC, antoniofilipovic requested changes
Small change and should be okay

2023-07-28 11:32 UTC, antoniofilipovic commented on cpp/map_module/algorithm/map.cpp
> +    const auto &value = arguments[2];
I am not sure, I saw that lot of things in our Memgraph codebase are constructed as `{}`, I tried to ask you guys on PRs to use that style but forget sometimes.

2023-07-28 11:32 UTC, antoniofilipovic approved these changes
Looks good to go

2023-07-28 13:12 UTC, merged