[E-ivan < T393] implement map.from_values
memgraph/mage pull request #267
Opened 2023-07-28 12:48 UTC by imilinovic

### Description
Implement map.from_values

### Pull request type

- [ ] Bugfix
- [X] Algorithm/Module
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Related issues

Delete if this PR doesn't resolve any issues. Link the issue if it does.

######################################

### Reviewer checklist (the reviewer checks this part)
#### Module/Algorithm
- [ ] Core algorithm/module implementation
- [ ] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [ ] End-to-end tests
- [ ] Code documentation
- [ ] README short description
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)
- [ ] Update GQLALchemy signatures in [query builder](https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/graph_algorithms/query_builder.py  ) using [query module signature generator](https://github.com/memgraph/gqlalchemy/blob/main/scripts/query_module_signature_generator.py)

######################################

2023-07-31 07:10 UTC, antoniofilipovic commented on cpp/map_module/algorithm/map.cpp
> +      ++ iterator;
`++iterator`

2023-07-31 07:11 UTC, antoniofilipovic commented on cpp/map_module/algorithm/map.cpp
> +      ++ iterator;
```suggestion
      ++iterator;
```

2023-07-31 07:11 UTC, antoniofilipovic commented on cpp/map_module/algorithm/map.cpp
> +      ++ iterator;
```suggestion
      ++iterator;
```

2023-07-31 07:11 UTC, antoniofilipovic requested changes
Small changes, otherwise looks good

2023-07-31 10:59 UTC, imilinovic commented on cpp/map_module/algorithm/map.cpp
> +std::string value_to_string(const mgp::Value &value) {
This function supports key being any type that isn't null, list, map or path. There wasn't a simple way to implement it (except null which can be ignored) but I don't think it's very important at the moment.
This function could perhaps be added inside mgp::Value

2023-07-31 14:57 UTC, antoniofilipovic commented on cpp/map_module/algorithm/map.cpp
> +      return "";
Can we support that via recursive calls? I think it makes sense to add that as part of mgp::Value and maybe overload operator << for mgp::Value directly. What do you think?

2023-08-02 08:15 UTC, antoniofilipovic approved these changes

2023-08-02 08:33 UTC, merged