[E-create < E-ivan] Imeplement create functions
memgraph/mage pull request #314
Opened 2023-08-10 23:59 UTC by imilinovic

### Description

Implement create functions

### Pull request type

- [ ] Bugfix
- [ ] Algorithm/Module
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

######################################

### Reviewer checklist (the reviewer checks this part)
#### Module/Algorithm
- [ ] Core algorithm/module implementation
- [ ] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [ ] End-to-end tests
- [ ] Code documentation
- [ ] README short description
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)
- [ ] Update GQLALchemy signatures in [query builder](https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/graph_algorithms/query_builder.py  ) using [query module signature generator](https://github.com/memgraph/gqlalchemy/blob/main/scripts/query_module_signature_generator.py)

######################################

2023-08-28 11:44 UTC, antoniofilipovic commented on cpp/create_module/algorithm/create.cpp
> +    auto ParseValue = [&](const mgp::Value &value) {
I would call this `ProcessValue`. Because if it is relationship you are modifying and outputting, otherwise you are inserting ids in list

2023-08-28 11:45 UTC, antoniofilipovic requested changes
One small change and that should be it

2023-08-30 13:51 UTC, antoniofilipovic approved these changes

2023-08-30 17:23 UTC, antepusic approved these changes

2023-08-30 17:23 UTC, antepusic commented on cpp/create_module/create_module.cpp
> +    AddProcedure(Create::SetRelProperties, Create::kProcedureSetRelProperties, mgp::ProcedureType::Write,
Blank line
```suggestion

    AddProcedure(Create::SetRelProperties, Create::kProcedureSetRelProperties, mgp::ProcedureType::Write,
```

2023-09-04 07:39 UTC, merged