[main < T load, parse] Implement xml.load and xml.parse
memgraph/mage pull request #329
Opened 2023-08-25 15:26 UTC by mpintaric55334

### Description

Please briefly explain the changes you made here.

### Pull request type

- [ ] Bugfix
- [x] Algorithm/Module
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Related issues

Delete if this PR doesn't resolve any issues. Link the issue if it does.

######################################

### Reviewer checklist (the reviewer checks this part)
#### Module/Algorithm
- [ ] Core algorithm/module implementation
- [ ] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [ ] End-to-end tests
- [ ] Code documentation
- [ ] README short description
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)
- [ ] Update GQLALchemy signatures in [query builder](https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/graph_algorithms/query_builder.py  ) using [query module signature generator](https://github.com/memgraph/gqlalchemy/blob/main/scripts/query_module_signature_generator.py)

######################################

2023-08-28 21:53 UTC, antepusic requested changes
This looks solid and does the job, just make sure to do this:

* change the tests to return something with a guaranteed order, not maps whose items’ ordering is not guaranteed
* format Python code

2023-08-28 21:53 UTC, antepusic commented on python/xml_module.py
> +    if(xpath):
```suggestion
    if xpath:
```

2023-08-28 21:53 UTC, antepusic commented on python/xml_module.py
> +    if path != "":
```suggestion
    if not path:
```

2023-08-28 21:53 UTC, antepusic commented on python/xml_module.py
> +    return result
Extract "_type", "_text" and "_children" to constants

2023-08-28 21:53 UTC, antepusic commented on python/xml_module.py
> +        if(simple): children_name = "_" + str(element.tag)
```suggestion
        if simple:
            children_name = "_" + str(element.tag)
```

2023-08-28 21:53 UTC, antepusic commented on python/xml_module.py
> +        raise OSError("Could not open or write to the file.")
```suggestion
        raise OSError("Could not open or write to file.")
```

2023-08-28 21:53 UTC, antepusic commented on python/xml_module.py
> +    if(not url.endswith(".xml")):
```suggestion
    if not url.endswith(".xml"):
```

2023-08-28 21:57 UTC, antepusic commented
@antoniofilipovic The tests use example XMLs from a third-party website. Thinking about reliability, I think it’s better to make our own example XMLs and host them on a Memgraph repo.

2023-08-29 18:58 UTC, mpintaric55334 commented on python/xml_module.py
> +    if path != "":
you mean if path

2023-08-29 19:02 UTC, mpintaric55334 commented
@antepusic @antoniofilipovic shouldnt the map order always be same in tests?

2023-08-30 10:37 UTC, antepusic reviewed
About map order:

2023-08-30 10:37 UTC, antepusic commented on python/xml_module.py
> +    if text_content and text_content.strip():
Nice

2023-08-30 13:45 UTC, antoniofilipovic commented
> mple XMLs from a third-party website. Thinking about reliability, I think it’s better to make our own example XMLs and host them on some Memgraph repo.

@antepusic I wouldn't do that for now. If it starts failing, we can check then.

2023-08-30 13:46 UTC, antoniofilipovic commented
> About map order: The map contains elements from `children`, whose value is taken from the `ElementTree` parsed by `.fromstring`.
> 
> ```
> result[children_name] = [
>     parse_element(child, simple) for child in children
> ]
> ```
> 
> After checking, I think their ordering is consistent so the tests are fine in that respect.

@antepusic so is PR ready to be merged or not?

2023-08-30 13:48 UTC, antepusic commented
It’s ready then! 🚀

2023-08-30 13:49 UTC, antepusic approved these changes

2023-09-07 10:36 UTC, merged