[E-algo < T518] Add algo.all_simple_paths
memgraph/mage pull request #356
Opened 2023-09-14 14:24 UTC by imilinovic

### Description

Add algo all_simple_paths

### Pull request type

- [ ] Bugfix
- [X] Algorithm/Module
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Related issues

Delete if this PR doesn't resolve any issues. Link the issue if it does.

######################################

### Reviewer checklist (the reviewer checks this part)
#### Module/Algorithm
- [ ] Core algorithm/module implementation
- [ ] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [ ] End-to-end tests
- [ ] Code documentation
- [ ] README short description
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)
- [ ] Update GQLALchemy signatures in [query builder](https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/graph_algorithms/query_builder.py  ) using [query module signature generator](https://github.com/memgraph/gqlalchemy/blob/main/scripts/query_module_signature_generator.py)

######################################

2023-09-19 10:57 UTC, imilinovic commented
Requires:
[Memgraph PR1249](https://github.com/memgraph/memgraph/pull/1249)

2023-10-26 13:22 UTC, antoniofilipovic commented on cpp/algo_module/algorithm/algo.cpp
> +  DFS(start_node_, path, visited);
Maybe BFS?

2023-10-26 13:43 UTC, antoniofilipovic requested changes
All looks good, but left two comments to make it more optimal

2023-10-26 13:43 UTC, antoniofilipovic commented on cpp/algo_module/algorithm/algo.cpp
> +    if (rel_type.size() == 1) {
Can you comment here if `<` or `>` is sent, then for all relationships `any_incoming_` or `any_outgoing_` works

2023-10-26 13:43 UTC, antoniofilipovic commented on cpp/algo_module/algorithm/algo.cpp
> +  visited.erase(curr_node.Id().AsInt());
Try to check here if user sent at all InRelationship, and if not that we don't expand on in relationships

2023-10-27 08:58 UTC, antoniofilipovic approved these changes

2023-10-30 10:19 UTC, merged