[main < T] Update readme
memgraph/mage pull request #366
Opened 2023-09-19 11:13 UTC by antoniofilipovic

### Description

We hadn't updated README for long time, lot of stuff were wrong here.

### Pull request type

- [ ] Bugfix
- [ ] Algorithm/Module
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Reviewer checklist (the reviewer checks this part)
#### Module/Algorithm
- [ ] Core algorithm/module implementation
- [ ] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [ ] End-to-end tests
- [ ] Code documentation
- [ ] README short description
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)
- [ ] Update GQLALchemy signatures in [query builder](https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/graph_algorithms/query_builder.py  ) using [query module signature generator](https://github.com/memgraph/gqlalchemy/blob/main/scripts/query_module_signature_generator.py)

######################################

2023-09-19 11:27 UTC, imilinovic commented on README.md
> +**0. b** Download memgraph from our official download site inside memgraph mage. Change ${MEMGRAPH_VERSION} with latest version Memgraph released, and
```suggestion
**0. b** Download Memgraph from our official download site inside Memgraph MAGE. Change ${MEMGRAPH_VERSION} with latest version Memgraph released, and
```

2023-09-19 11:31 UTC, imilinovic commented on README.md
> +**0. b** Download memgraph from our official download site inside memgraph mage. Change ${MEMGRAPH_VERSION} with latest version Memgraph released, and
I don't find the first sentence very clear, if my understanding is correct would suggest
```suggestion
**0. b** Download Memgraph from our official site inside your cloned MAGE repository. Change ${MEMGRAPH_VERSION} with latest version Memgraph released, and
```

2023-09-19 11:33 UTC, imilinovic commented on README.md
> +Run following command to install rust and python dependencies:
```suggestion
Run the following command to install rust and python dependencies:
```

2023-09-19 11:34 UTC, imilinovic commented on README.md
> +Now you can run this command to compile and copy all C++ and Rust modules, and copy Python modules to following path `/usr/lib/memgraph/query_modules`.
```suggestion
Now you can run this command to compile and copy all C++ and Rust modules, and copy Python modules to the following path `/usr/lib/memgraph/query_modules`.
```

2023-09-19 11:37 UTC, imilinovic requested changes
Small changes

2023-09-19 11:57 UTC, antepusic requested changes

2023-09-19 11:57 UTC, antepusic commented on README.md
>  | >= 1.4 | >= 2.4.0 |
Fix table:
```suggestion
| MAGE version | Memgraph version |
| ------------ | ---------------- |
| >= 1.11.9    | >= 2.11.0        |
| >= 1.5.1     | >= 2.5.1         |
| >= 1.5       | >= 2.5.0         |
| >= 1.4       | >= 2.4.0         |
```

2023-09-19 11:57 UTC, antepusic commented on README.md
> +**0. b** Download memgraph from our official download site inside memgraph mage. Change ${MEMGRAPH_VERSION} with latest version Memgraph released, and
Another clarification:
```suggestion
**0. b** Download Memgraph from our official download site inside your cloned MAGE repository. Set ${MEMGRAPH_VERSION} to the latest release of Memgraph, and
```

2023-09-19 11:57 UTC, antepusic commented on README.md
> +curl -L "https://download.memgraph.com/memgraph/v${MEMGRAPH_VERSION}/debian-11/memgraph_${MEMGRAPH_VERSION}-1_amd64.deb" > memgraph-amd64.deb
```suggestion
${ARCHITECTURE} to your system architecture (`amd64` or `arm64`):

```bash

curl -L "https://download.memgraph.com/memgraph/v${MEMGRAPH_VERSION}/debian-11/memgraph_${MEMGRAPH_VERSION}-1_${ARCHITECTURE}.deb" > memgraph-${ARCHITECTURE}.deb
```

2023-09-19 11:57 UTC, antepusic commented on README.md
> +**1.** To build the **MAGE** image run the following command where you change ${architecture} with `amd64` or `arm64`, depending on which system you are.
```suggestion
**1.** To build the **MAGE** image run the following command where you set ${architecture} to your system architecture (`amd64` or `arm64`):
```

2023-09-19 11:57 UTC, antepusic commented on README.md
> +Now you can run this command to compile and copy all C++ and Rust modules, and copy Python modules to following path `/usr/lib/memgraph/query_modules`.
The sentence is a little confusing so I simplified it:
```suggestion
Now you can run the following command to compile and copy the query modules to the `/usr/lib/memgraph/query_modules` path:
```

2023-11-21 17:13 UTC, antepusic approved these changes
The new text reads much better :+1:

2023-11-28 12:28 UTC, merged