[E-algo < T581] Implement algo.cover
memgraph/mage pull request #389
Opened 2023-10-11 16:20 UTC by mpintaric55334

### Description

Please briefly explain the changes you made here.

### Pull request type

- [ ] Bugfix
- [ ] Algorithm/Module
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Related issues

Delete if this PR doesn't resolve any issues. Link the issue if it does.

######################################

### Reviewer checklist (the reviewer checks this part)
#### Module/Algorithm
- [ ] Core algorithm/module implementation
- [ ] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [ ] End-to-end tests
- [ ] Code documentation
- [ ] README short description
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)
- [ ] Update GQLALchemy signatures in [query builder](https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/graph_algorithms/query_builder.py  ) using [query module signature generator](https://github.com/memgraph/gqlalchemy/blob/main/scripts/query_module_signature_generator.py)

######################################

2023-10-16 09:23 UTC, antoniofilipovic approved these changes
Looks good to me

2023-10-16 09:24 UTC, antoniofilipovic commented
@mpintaric55334 don't forget to update description and ping Vlasta

2023-10-16 22:00 UTC, imilinovic commented on cpp/algo_module/algorithm/algo.cpp
> +      for (auto rel : node.OutRelationships()) {
You can use const auto &node and const auto rel

2023-10-16 22:00 UTC, imilinovic requested changes
One small change

2023-10-16 22:01 UTC, imilinovic commented on cpp/algo_module/algorithm/algo.cpp
> +    for (const auto elem : list_nodes) {
You can use const auto &elem

2023-10-23 10:46 UTC, imilinovic approved these changes
Looks good to go!

2023-10-23 10:48 UTC, merged