Add CSV utility functions used in the Lab CSV import feature
memgraph/mage pull request #401
Opened 2023-10-24 07:53 UTC by cizl

### Description

Please briefly explain the changes you made here.

### Pull request type

- [ ] Bugfix
- [ ] Algorithm/Module
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Related issues

Delete if this PR doesn't resolve any issues. Link the issue if it does.

######################################

### Reviewer checklist (the reviewer checks this part)
#### Module/Algorithm
- [ ] Core algorithm/module implementation
- [ ] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [ ] End-to-end tests
- [ ] Code documentation
- [ ] README short description
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)
- [ ] Update GQLALchemy signatures in [query builder](https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/graph_algorithms/query_builder.py  ) using [query module signature generator](https://github.com/memgraph/gqlalchemy/blob/main/scripts/query_module_signature_generator.py)

######################################

2023-10-24 18:22 UTC, mpintaric55334 requested changes
Wasn't tagged as reviewer, but was checking MAGE PR'S, so I left a few comments.

2023-10-24 18:22 UTC, mpintaric55334 commented on cpp/csv_utils_module/algorithm/csv_utils.cpp
> +  mgp::memory = memory;
Im not tagged as reviewer, but was "around", you dont need mgp::memory = memory;, that will be deprecated soon, DispatcherGuard is enough

2023-10-24 18:22 UTC, mpintaric55334 commented on cpp/csv_utils_module/algorithm/csv_utils.cpp
> +  mgp::memory = memory;
Same comment about memory.

2023-10-24 18:22 UTC, mpintaric55334 commented on cpp/csv_utils_module/csv_utils_module.cpp
> +    mgp::memory = memory;
Same comment about memory, we use MemoryDispatcherGuard instead

2023-10-24 18:22 UTC, mpintaric55334 commented on cpp/csv_utils_module/algorithm/csv_utils.cpp
> +    mgp::List return_list;
Does this list do anything or used anywhere?

2023-10-25 12:00 UTC, antoniofilipovic commented
@cizl is this ready for review or a work in progress? Because on PR you put WIP and on status ready :smile:

2023-10-26 07:40 UTC, cizl commented
> @cizl is this ready for review or a work in progress? Because on PR you put WIP and on status ready 😄

Sorry about that, forgot to remove it from the title. :sweat_smile: 
Feel free to take a look!

2023-10-26 07:41 UTC, cizl commented
> Wasn't tagged as reviewer, but was checking MAGE PR'S, so I left a few comments.

Nice! Thanks a bunch for taking a look :smile:

2023-10-26 08:07 UTC, mpintaric55334 approved these changes
LGTM! I just added empty lines to the end of the files and resolved the conflict in CMakeLists.txt so we dont't play PR ping pong over an empty line change.

2023-10-27 09:04 UTC, antoniofilipovic requested changes
All looks good, left few final comments

2023-10-27 09:04 UTC, antoniofilipovic commented on cpp/csv_utils_module/algorithm/csv_utils.cpp
> +    const std::string_view filepath = arguments[0].ValueString();
You can use `const auto` here, as your are using for other variables too

2023-10-27 09:04 UTC, antoniofilipovic commented on cpp/csv_utils_module/algorithm/csv_utils.cpp
> +    const auto isAppend = arguments[2].ValueBool();
Use snake case for variable naming
```suggestion
    const auto is_append = arguments[2].ValueBool();
```

2023-10-27 09:04 UTC, antoniofilipovic commented on cpp/csv_utils_module/algorithm/csv_utils.cpp
> +    return;
Unnecessary return here as you have one below

2023-10-27 10:43 UTC, antoniofilipovic approved these changes

2023-10-27 12:01 UTC, merged