Add periodic iterate fix on authentication
memgraph/mage pull request #407
Opened 2023-11-01 20:25 UTC by Josipmrden

### Description

Periodic iterate has not been able to execute queries in an authenticated environment because on one of the paths the client has been connecting to Memgraph without username and password provided. That path has now been covered to provide credentials based on environment variables.

### Pull request type

- [X] Bugfix

### Related issues

Delete if this PR doesn't resolve any issues. Link the issue if it does.

######################################

### Reviewer checklist (the reviewer checks this part)
#### Module/Algorithm
- [ ] Core algorithm/module implementation
- [ ] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [ ] End-to-end tests
- [ ] Code documentation
- [ ] README short description
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)
- [ ] Update GQLALchemy signatures in [query builder](https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/graph_algorithms/query_builder.py  ) using [query module signature generator](https://github.com/memgraph/gqlalchemy/blob/main/scripts/query_module_signature_generator.py)

######################################

2023-11-09 09:59 UTC, antejavor requested changes
Let's just make password and username env variables consistent between Memgraph and Mage, so we do not have duplicates.

2023-11-09 15:20 UTC, Josipmrden commented
@antejavor please create a community issue for this so engineering team can take this over

2023-11-29 14:13 UTC, antejavor commented
@Josipmrden I have added the initial issue to the community projects.

2023-12-05 08:47 UTC, vpavicic commented
RN: Periodic iterate is now executed in an authenticated environment as
  expected.

2024-01-11 13:31 UTC, katarinasupe commented
@Josipmrden is this PR fixing the issue + if it is, does it fix other similar issues too? https://github.com/memgraph/mage/issues/424

2024-01-12 10:42 UTC, vpavicic commented
@Josipmrden is this a part of the 2.14 release or should I just remove the milestone? :D

2024-03-13 10:06 UTC, antoniofilipovic commented
@Josipmrden what is status with this PR?

2024-04-12 09:00 UTC, Josipmrden commented
With v2.16, this is now fixed by another PR

2024-04-12 09:00 UTC, closed without merging