Add set property module
memgraph/mage pull request #445
Opened 2024-02-23 12:00 UTC by Josipmrden

### Description

Add set property module to MAGE

### Pull request type

- [ ] Bugfix
- [X] Algorithm/Module
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

######################################

### Reviewer checklist (the reviewer checks this part)
#### Module/Algorithm
- [X] Core algorithm/module implementation
- [X] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [X] End-to-end tests
- [X] Code documentation
- [X] README short description
- [X] Documentation on [memgraph/docs](https://github.com/memgraph/docs)
- [ ] Update GQLALchemy signatures in [query builder](https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/graph_algorithms/query_builder.py  ) using [query module signature generator](https://github.com/memgraph/gqlalchemy/blob/main/scripts/query_module_signature_generator.py)

######################################

2024-02-26 07:21 UTC, antepusic approved these changes
All looks good (had to leave one suggestion :smile:)

2024-03-11 11:47 UTC, antepusic approved these changes
All should be good now :heavy_check_mark:

2024-03-11 16:10 UTC, antoniofilipovic requested changes
Good work, I think GetClientParams is slightly off

2024-03-11 16:10 UTC, antoniofilipovic commented on cpp/set_property_module/set_property_module.cpp
> +    password = std::move(maybe_password);
no need for std::move as you are copying pointer, and it is just variable copy

2024-03-11 16:10 UTC, antoniofilipovic commented on cpp/set_property_module/set_property_module.cpp
> +}
mg::Client::Params accepts string and you are moving pointer.  I think correct solution is following
```suggestion
  return mg::Client::Params{.host = std::string(host),
                            .port = port,
                            .username = std::string(username),
                            .password = std::string(password)};
}
```

2024-03-11 16:10 UTC, antoniofilipovic commented on cpp/set_property_module/set_property_module.cpp
> +  auto *password = "";
You can just init struct here mg::Client::Params{...} and then update struct element if you find env variable

2024-03-12 17:23 UTC, Josipmrden commented
@antoniofilipovic  Do check when you have time!

2024-03-13 10:04 UTC, antoniofilipovic approved these changes
Looks good

2024-03-13 12:58 UTC, merged