Periodic delete
memgraph/mage pull request #446
Opened 2024-02-23 17:55 UTC by Josipmrden

### Description

Periodic delete as a workaround for large number of deltas during deletion

### Pull request type

- [ ] Bugfix
- [X] Algorithm/Module
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

######################################

### Reviewer checklist (the reviewer checks this part)
#### Module/Algorithm
- [X] Core algorithm/module implementation
- [X] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [X] End-to-end tests
- [X] Code documentation
- [X] README short description
- [X] Documentation on [memgraph/docs](https://github.com/memgraph/docs)
- [ ] Update GQLALchemy signatures in [query builder](https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/graph_algorithms/query_builder.py  ) using [query module signature generator](https://github.com/memgraph/gqlalchemy/blob/main/scripts/query_module_signature_generator.py)

######################################

2024-03-11 13:34 UTC, antepusic requested changes
Good job, the query module logic is sound and everything else is fine as well. :+1: 

I’ve only had a few comments about avoiding duplication, and please add a test where you delete nodes with a specific label (or repurpose `test_periodic_delete_on_just_nodes` for that

2024-03-11 16:16 UTC, antoniofilipovic commented on cpp/periodic_module/periodic.cpp
> +}
Same comment as for #445 PR

2024-03-11 16:34 UTC, antoniofilipovic commented on cpp/periodic_module/periodic.cpp
> +      vec.emplace_back(std::string(value.ValueString()));
You don't need std::string, as a `value.ValueString()` returns std::string_view and it will be constructed in place:
https://godbolt.org/z/94Kz5sM1n

2024-03-11 16:35 UTC, antoniofilipovic commented on cpp/periodic_module/periodic.cpp
> +void ExecutePeriodicDelete(DeletionInfo deletion_info, DeletionResult &deletion_result) {
You can accept here by const &, and then you don't need to move, as this way we need move ctor, and other with const &, it is just variable creation

2024-03-11 16:59 UTC, antoniofilipovic requested changes
Few suggestions, otherwise good work :muscle:

2024-03-12 17:47 UTC, Josipmrden commented on cpp/periodic_module/periodic.cpp
I'm not sure what you mean on the first comment

2024-03-12 17:52 UTC, Josipmrden commented
@antepusic  @antoniofilipovic  Pls review again!

2024-03-12 18:18 UTC, antepusic commented on cpp/periodic_module/periodic.cpp
About the first comment: `ValidateBatchSize` and `ValidateDeletionConfig` have different checks & error messages for the `batch_size` parameter. I advise to make them consistent, and then to extract that into its own function to avoid repeated code.

2024-03-12 18:20 UTC, antepusic requested changes
Made the comment in https://github.com/memgraph/mage/pull/446/files#r1521938923 clearer, just make sure to address it

2024-03-13 09:28 UTC, antepusic approved these changes
I think all’s good now :heavy_check_mark:

2024-03-13 10:01 UTC, antoniofilipovic approved these changes

2024-03-18 09:36 UTC, merged