Add postgresql migration
memgraph/mage pull request #464
Opened 2024-04-18 12:44 UTC by Josipmrden

### Description

Postgresql migration module has been added.

### Pull request type

- [ ] Bugfix
- [X] Algorithm/Module
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Related issues
X

######################################

### Reviewer checklist (the reviewer checks this part)
#### Module/Algorithm
- [ ] Core algorithm/module implementation
- [ ] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Tests provided (unit / e2e)
- [ ] Code documentation
- [ ] README short description

### Documentation checklist
- [ ] Add the documentation label tag
- [ ] Add the bug / feature label tag
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[Release note text]**
- [ ] Link the documentation PR here
    - **[Documentation PR link]**
- [ ] Tag someone from docs team in the comments

2024-05-29 11:06 UTC, antoniofilipovic commented on python/migrate.py
> +    postgres_dict[threading.get_native_id][Constants.CONNECTION].commit()
Can you revert these two, I think Buda correctly noticed once that we need first to commit and then close, this was bug

2024-05-29 11:06 UTC, antoniofilipovic requested changes
Just one change

2024-05-29 12:26 UTC, antoniofilipovic approved these changes
LGMT

2024-06-06 11:30 UTC, merged

2024-06-06 11:30 UTC, Josipmrden commented
@kgolubic  I still need to add documentation, pls remind if I don't create it

2024-06-13 09:11 UTC, kgolubic commented
@Josipmrden reminder for the docs.

2024-06-19 09:17 UTC, kgolubic commented
I will use this as Release note:

- Added a PostgreSQL migration module to MAGE that enables direct migration from
  a PostgreSQL database to Memgraph. This new module streamlines the data import
  process by reducing the need for intermediate steps, such as using CSV files.
  Users can now migrate tables, including nodes and relationships, directly into
  Memgraph. 
  [#464](https://github.com/memgraph/mage/pull/464)